### ISSUE TITLE
Change xmobar temperature to show Celsius.

### ISSUE THREAD

**Issue by rbasso** [rbasso/dotfiles#7]

**Comment by R0binvd** [comment]
Edit the run section of the .xmobarrc file to look like this:

`Run Weather "EGPF" ["-t"," <tempC>C","-L","64","-H","77","--normal","green","--high","red","--low","lightblue"] 36000`

only the <tempC>C matters, hope this helps

**Comment by rbasso** [comment]
Thank you!
:+1:
